/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import simcards.*;
import Models.Render;
import java.sql.ResultSet;
import javax.naming.spi.DirStateFactory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Datos_Clientes extends javax.swing.JDialog {

    /**
     * Creates new form Crear_Operador
     */
    private DefaultTableModel modeloDeMiJTable; 
    public Datos_Clientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(660,330);
        setTitle("Datos Basicos");
        setLocationRelativeTo(rootPane);
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_nombre1 = new javax.swing.JTextField();
        jTextField_nombre2 = new javax.swing.JTextField();
        jTextField_nombre3 = new javax.swing.JTextField();
        jTextField_nombre4 = new javax.swing.JTextField();
        jTextField_nombre5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField_nombre6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_nombre7 = new javax.swing.JTextField();
        jTextField_nombre8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_nombre9 = new javax.swing.JTextField();
        jTextField_nombre10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField_nombre11 = new javax.swing.JTextField();
        jTextField_nombre12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 100, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1396514213_Remove.png"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 250, 160, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Barrio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 140, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 190, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("CC / Nit");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 110, 190, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Direccion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 110, 90, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Ciudad");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 140, 190, 30);

        jTextField_nombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre1);
        jTextField_nombre1.setBounds(140, 40, 490, 30);

        jTextField_nombre2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre2);
        jTextField_nombre2.setBounds(140, 80, 490, 30);

        jTextField_nombre3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre3);
        jTextField_nombre3.setBounds(140, 110, 180, 30);

        jTextField_nombre4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre4);
        jTextField_nombre4.setBounds(410, 140, 220, 30);

        jTextField_nombre5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre5);
        jTextField_nombre5.setBounds(140, 140, 180, 30);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1402870079_floppy.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 250, 160, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setText("Nombre");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(230, -1, 120, 40);

        jTextField_nombre6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre6);
        jTextField_nombre6.setBounds(410, 110, 220, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Celular");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 170, 90, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Dar Credito?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 200, 150, 30);

        jTextField_nombre7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre7);
        jTextField_nombre7.setBounds(410, 170, 220, 30);

        jTextField_nombre8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre8);
        jTextField_nombre8.setBounds(140, 170, 180, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Celular");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 170, 90, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Telefono");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 170, 190, 30);

        jTextField_nombre9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre9);
        jTextField_nombre9.setBounds(410, 170, 220, 30);

        jTextField_nombre10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre10);
        jTextField_nombre10.setBounds(140, 170, 180, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Telefono");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 170, 190, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton3.setText("Cedula");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(140, -1, 80, 40);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton4.setText("No");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(210, 200, 50, 30);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton5.setText("Si");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(160, 200, 40, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cupo Maximo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 200, 140, 30);

        jTextField_nombre11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre11);
        jTextField_nombre11.setBounds(410, 200, 220, 30);

        jTextField_nombre12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField_nombre12);
        jTextField_nombre12.setBounds(410, 200, 220, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1396515201_document-edit.png"))); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 250, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    Conexion conn = new Conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField_nombre1;
    private javax.swing.JTextField jTextField_nombre10;
    private javax.swing.JTextField jTextField_nombre11;
    private javax.swing.JTextField jTextField_nombre12;
    private javax.swing.JTextField jTextField_nombre2;
    private javax.swing.JTextField jTextField_nombre3;
    private javax.swing.JTextField jTextField_nombre4;
    private javax.swing.JTextField jTextField_nombre5;
    private javax.swing.JTextField jTextField_nombre6;
    private javax.swing.JTextField jTextField_nombre7;
    private javax.swing.JTextField jTextField_nombre8;
    private javax.swing.JTextField jTextField_nombre9;
    // End of variables declaration//GEN-END:variables
}
