/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package simcards;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Crear_Simcard extends javax.swing.JDialog {

    /**
     * Creates new form Crear_Operador
     */
    private DefaultTableModel modeloDeMiJTable; 
    public Crear_Simcard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(1000,700);
        setTitle("Creacion Plan");
        setLocationRelativeTo(rootPane);
        modeloDeMiJTable = new DefaultTableModel() { 
        @Override 
        public Class getColumnClass(int c) { 
        return getValueAt(0, c).getClass(); 
        } 

        @Override 
        public boolean isCellEditable(int rowIndex, int columnIndex) { 
        return false; 
        }

        };
        
        modeloDeMiJTable.addColumn("CODIGO");
        modeloDeMiJTable.addColumn("SERIAL");
        modeloDeMiJTable.addColumn("OPERADOR");
        modeloDeMiJTable.addColumn("# LINEA");
        modeloDeMiJTable.addColumn("VALOR");
        modeloDeMiJTable.addColumn("CORTE");
        modeloDeMiJTable.addColumn("ESTADO");
        modeloDeMiJTable.addColumn("PLAN");
        modeloDeMiJTable.addColumn("EMPRESA");
        modeloDeMiJTable.addColumn("SALDO");
        modeloDeMiJTable.addColumn("REF PAGO");
        jTable1.setModel(modeloDeMiJTable);
        int[] anchos = {10, 10, 30,30,30,10,30,50,30,30,30};
        for(int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        jButton_ELIMINAR.setEnabled(false);
        llenartabla();
        buscar_operador();
        jTextField_cant.setEditable(false);
    }
    public void buscar_operador(){
        Vector cliente = new Vector();
        try{
         conn.establecer_conexion();
         String sql="select nombre from operador";
         ResultSet resultado = conn.consulta(sql);
         cliente.addElement("Seleccione un Operador");
         while(resultado.next()){
             cliente.addElement(resultado.getString(1));
         }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(cliente));
        jPanel1.add(jComboBox1);
        }catch(Exception e){
            
        }
    }
    public void llenartabla(){

        conn.establecer_conexion();
        String consulta="select * from simcard where estado=1";
        ResultSet n=conn.consulta(consulta);
        try{
        while(n.next()){
            ResultSet m=conn.consulta("select nombre from operador where id="+n.getString(3));
            while(m.next()){
            modeloDeMiJTable.addRow(new Object[]{n.getString(2),m.getString(1),n.getString(4),n.getString(5),n.getString(6),n.getString(7),n.getString(8)});
            }
        }
        }
        catch(Exception e){}
        jTextField_cant.setText(String.valueOf(jTable1.getRowCount()));
        Vector plan= new Vector();
      String operador=jComboBox1.getSelectedItem().toString();
      String consulta2="select nombre from empresa";
      plan.addElement("Seleccione una Empresa");
      ResultSet n2= conn.consulta(consulta2);
        try {
            while(n2.next()){
                plan.addElement(n2.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Crear_Simcard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(plan));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_nlinea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_corte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_vlrcliente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_vlrplan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_min = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_serial = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_vlrbolsa = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jTextField_saldo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_refpago = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_ELIMINAR = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_cant = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 960, 150);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Datos del Plan", 3, 0, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("N° Linea");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 240, 30);

        jTextField_nlinea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_nlinea);
        jTextField_nlinea.setBounds(120, 100, 210, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Operador");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 110, 30);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(120, 40, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Empresa");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 130, 240, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Plan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 70, 110, 30);

        jTextField_codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_codigo);
        jTextField_codigo.setBounds(430, 40, 130, 30);

        jTextField_corte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_corte);
        jTextField_corte.setBounds(430, 70, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Serial");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 100, 200, 30);

        jTextField_vlrcliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_vlrcliente);
        jTextField_vlrcliente.setBounds(680, 40, 270, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Vlr Cliente");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(580, 40, 130, 30);

        jTextField_vlrplan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_vlrplan);
        jTextField_vlrplan.setBounds(680, 100, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Vlr Plan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(580, 100, 240, 30);

        jTextField_min.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_min);
        jTextField_min.setBounds(860, 100, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Min");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(810, 100, 50, 30);

        jTextField_serial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_serial);
        jTextField_serial.setBounds(430, 100, 130, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1396849974_trash yellow.png"))); // NOI18N
        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 170, 160, 40);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un plan" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(120, 70, 210, 30);

        jComboBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Asignada", "Disponible" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(430, 130, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Codigo");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(340, 40, 200, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Corte");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 70, 200, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Estado");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(340, 130, 200, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Vlr Bolsa");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(580, 70, 130, 30);

        jTextField_vlrbolsa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_vlrbolsa);
        jTextField_vlrbolsa.setBounds(680, 70, 270, 30);

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Empresa" }));
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(120, 130, 210, 30);

        jTextField_saldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_saldo);
        jTextField_saldo.setBounds(860, 130, 90, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Saldo");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(810, 130, 50, 30);

        jTextField_refpago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField_refpago);
        jTextField_refpago.setBounds(680, 130, 120, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Ref Pago");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(580, 130, 240, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 970, 230);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TOTAL PLANES");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 530, 200, 50);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1396515201_document-edit.png"))); // NOI18N
        jButton1.setText("EDITAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(820, 280, 160, 40);

        jButton_ELIMINAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1396514213_Remove.png"))); // NOI18N
        jButton_ELIMINAR.setText("ELIMINAR");
        jButton_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ELIMINAR);
        jButton_ELIMINAR.setBounds(20, 550, 160, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("SIMCARDS EXISTENTES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 310, 960, 30);

        jTextField_cant.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_cant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_cant);
        jTextField_cant.setBounds(870, 540, 100, 30);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1402870079_floppy.png"))); // NOI18N
        jButton4.setText("GUARDAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 280, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ELIMINARActionPerformed

    }//GEN-LAST:event_jButton_ELIMINARActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Object [] validar = {jTextField_cant.getText()};
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
 
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
      Vector plan= new Vector();
      String operador=jComboBox1.getSelectedItem().toString();
      String consulta="select nombre from plan where operador=(select id from operador where nombre='"+operador+"');";
      plan.addElement("Seleccione un plan");
      ResultSet n= conn.consulta(consulta);
        try {
            while(n.next()){
                plan.addElement(n.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Crear_Simcard.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(plan));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    Conexion conn = new Conexion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_ELIMINAR;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_cant;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_corte;
    private javax.swing.JTextField jTextField_min;
    private javax.swing.JTextField jTextField_nlinea;
    private javax.swing.JTextField jTextField_refpago;
    private javax.swing.JTextField jTextField_saldo;
    private javax.swing.JTextField jTextField_serial;
    private javax.swing.JTextField jTextField_vlrbolsa;
    private javax.swing.JTextField jTextField_vlrcliente;
    private javax.swing.JTextField jTextField_vlrplan;
    // End of variables declaration//GEN-END:variables
}
