/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Usuario
 */
public class Add_Estudiante extends javax.swing.JDialog {

    /**
     * Creates new form HojaEstudiante
     */
    public Add_Estudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(870, 500);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_salon = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_estado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_salon1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField_codigo1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Codigo Estudiante");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 190, 40);

        jTextField_codigo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_codigo);
        jTextField_codigo.setBounds(220, 100, 470, 40);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 40)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AGREGAR ESTUDIANTES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 10, 670, 80);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Lugar Nacimiento");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 250, 190, 40);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Edad");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 200, 190, 40);

        jTextField_salon.setEditable(false);
        jTextField_salon.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_salon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_salonActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_salon);
        jTextField_salon.setBounds(220, 200, 140, 40);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setText("Dirección");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 350, 190, 40);

        jTextField_estado.setEditable(false);
        jTextField_estado.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_estadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_estado);
        jTextField_estado.setBounds(220, 350, 240, 40);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel19.setText("Fecha Nacimiento");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 300, 190, 40);

        jTextField_salon1.setEditable(false);
        jTextField_salon1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_salon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_salon1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_salon1);
        jTextField_salon1.setBounds(220, 300, 240, 40);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/16.png"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(490, 170, 200, 250);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add_estudiante.png"))); // NOI18N
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 330, 110, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Value_estudiante.png"))); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 230, 110, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Photo_estudiante.png"))); // NOI18N
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 130, 110, 100);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clean_estudiante.png"))); // NOI18N
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 30, 110, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(720, 10, 130, 440);

        jTextField_codigo1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_codigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigo1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_codigo1);
        jTextField_codigo1.setBounds(220, 150, 240, 40);

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE UN MUNICIPIO", "MEDELLIN", "ABEJORRAL", "ABRIAQUI", "ALEJANDRIA", "AMAGA", "AMALFI", "ANDES", "ANGELOPOLIS", "ANGOSTURA", "ANORI", "SANTA FE DE ANTIOQUIA", "ANZA", "APARTADO", "ARBOLETES", "ARGELIA", "ARMENIA", "BARBOSA", "BELMIRA", "BELLO", "BETANIA", "BETULIA", "CIUDAD BOLIVAR", "BRICENO", "BURITICA", "CACERES", "CAICEDO", "CALDAS", "CAMPAMENTO", "CANASGORDAS", "CARACOLI", "CARAMANTA", "CAREPA", "CARMEN DE VIBORAL", "CAROLINA", "CAUCASIA", "CHIGORODO", "CISNEROS", "COCORNA", "CONCEPCION", "CONCORDIA", "COPACABANA", "DABEIBA", "DON MATIAS", "EBEJICO", "EL BAGRE", "ENTRERRIOS", "ENVIGADO", "FREDONIA", "FRONTINO", "GIRALDO", "GIRARDOTA", "GOMEZ PLATA", "GRANADA", "GUADALUPE", "GUARNE", "GUATAPE", "HELICONIA", "HISPANIA", "ITAGÜI", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 250, 240, 40);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Nombre Estudiante");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 100, 190, 40);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Convive con?");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 400, 190, 40);

        jComboBox2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "MADRE", "PADRE", "FAMILIAR" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 400, 240, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoActionPerformed

    }//GEN-LAST:event_jTextField_codigoActionPerformed

    private void jTextField_salonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_salonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_salonActionPerformed

    private void jTextField_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_estadoActionPerformed

    private void jTextField_salon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_salon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_salon1ActionPerformed

    private void jTextField_codigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codigo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_codigo1;
    private javax.swing.JTextField jTextField_estado;
    private javax.swing.JTextField jTextField_salon;
    private javax.swing.JTextField jTextField_salon1;
    // End of variables declaration//GEN-END:variables
}
