/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Usuario
 */
public class View_Padre extends javax.swing.JDialog {

    /**
     * Creates new form HojaEstudiante
     */
    public View_Padre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(870, 720);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField_nombrepadre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_telefonopadre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_celularpadre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_correopadre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_direccionpadre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_correopadre1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField_correopadre2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_correopadre3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_correopadre4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_correopadre5 = new javax.swing.JTextField();
        jTextField_correopadre6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Nombre Completo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 160, 180, 40);

        jTextField_nombrepadre.setEditable(false);
        jTextField_nombrepadre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_nombrepadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombrepadreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_nombrepadre);
        jTextField_nombrepadre.setBounds(220, 160, 470, 40);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 180, 40);

        jTextField_telefonopadre.setEditable(false);
        jTextField_telefonopadre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_telefonopadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonopadreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_telefonopadre);
        jTextField_telefonopadre.setBounds(220, 210, 180, 40);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Celular");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 210, 90, 40);

        jTextField_celularpadre.setEditable(false);
        jTextField_celularpadre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_celularpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_celularpadreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_celularpadre);
        jTextField_celularpadre.setBounds(510, 210, 180, 40);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setText("Dirección Casa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 260, 180, 40);

        jTextField_correopadre.setEditable(false);
        jTextField_correopadre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre);
        jTextField_correopadre.setBounds(220, 260, 470, 40);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Tipo de Familiar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 60, 180, 40);

        jTextField_direccionpadre.setEditable(false);
        jTextField_direccionpadre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_direccionpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_direccionpadreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_direccionpadre);
        jTextField_direccionpadre.setBounds(220, 110, 470, 40);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel9.setText("Dirección Oficina");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 510, 180, 40);

        jTextField_correopadre1.setEditable(false);
        jTextField_correopadre1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadre1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre1);
        jTextField_correopadre1.setBounds(220, 510, 470, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 24))); // NOI18N
        jPanel1.setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Estudiante_PRINT.png"))); // NOI18N
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 460, 110, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clean_estudiante.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(10, 130, 110, 100);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Change_estudiante.png"))); // NOI18N
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 240, 110, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Add_estudiante.png"))); // NOI18N
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 350, 110, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(720, 10, 130, 670);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Barrio");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 310, 180, 40);

        jTextField_correopadre2.setEditable(false);
        jTextField_correopadre2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadre2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre2);
        jTextField_correopadre2.setBounds(220, 310, 470, 40);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Nivel Educación");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 410, 180, 40);

        jTextField_correopadre3.setEditable(false);
        jTextField_correopadre3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadre3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre3);
        jTextField_correopadre3.setBounds(220, 360, 470, 40);

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONA NIVEL DE ESTUDIOS", "PRIMARIA", "SECUNDARIA", "UNIVERSITARIOS", "NO TIENE", "OTRO", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(220, 410, 290, 40);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("E-mail");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 360, 180, 40);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel13.setText("Título");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 460, 180, 40);

        jTextField_correopadre4.setEditable(false);
        jTextField_correopadre4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadre4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre4);
        jTextField_correopadre4.setBounds(220, 460, 470, 40);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel14.setText("Empresa Donde Labora");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 560, 190, 40);

        jTextField_correopadre5.setEditable(false);
        jTextField_correopadre5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadre5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre5);
        jTextField_correopadre5.setBounds(220, 560, 470, 40);

        jTextField_correopadre6.setEditable(false);
        jTextField_correopadre6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTextField_correopadre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correopadre6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_correopadre6);
        jTextField_correopadre6.setBounds(220, 610, 470, 40);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Cargo");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 610, 190, 40);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel16.setText("Cedula");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 110, 180, 40);

        jComboBox2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE UN TIPO", "MADRE", "PADRE", "OTRO" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 60, 300, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nombrepadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombrepadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombrepadreActionPerformed

    private void jTextField_telefonopadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonopadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonopadreActionPerformed

    private void jTextField_celularpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_celularpadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_celularpadreActionPerformed

    private void jTextField_correopadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadreActionPerformed

    private void jTextField_direccionpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_direccionpadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_direccionpadreActionPerformed

    private void jTextField_correopadre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadre1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add_Estudiante dialog = new Add_Estudiante(new javax.swing.JFrame(), true);
                
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_correopadre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadre2ActionPerformed

    private void jTextField_correopadre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadre3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadre3ActionPerformed

    private void jTextField_correopadre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadre4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadre4ActionPerformed

    private void jTextField_correopadre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadre5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadre5ActionPerformed

    private void jTextField_correopadre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correopadre6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correopadre6ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_celularpadre;
    private javax.swing.JTextField jTextField_correopadre;
    private javax.swing.JTextField jTextField_correopadre1;
    private javax.swing.JTextField jTextField_correopadre2;
    private javax.swing.JTextField jTextField_correopadre3;
    private javax.swing.JTextField jTextField_correopadre4;
    private javax.swing.JTextField jTextField_correopadre5;
    private javax.swing.JTextField jTextField_correopadre6;
    private javax.swing.JTextField jTextField_direccionpadre;
    private javax.swing.JTextField jTextField_nombrepadre;
    private javax.swing.JTextField jTextField_telefonopadre;
    // End of variables declaration//GEN-END:variables
}
