/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Cartera_y_caja;

import Administrativo.*;
import inmobiliaria_fase01.Conexion;
import java.awt.Rectangle;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Usuario
 */
public class Saldos extends javax.swing.JDialog {
private DefaultTableModel modeloDeMiJTable; 
    
    public Saldos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(850,600);
        setTitle("Saldo Deudores");
        this.setLocationRelativeTo(null);
        JDialog.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.NebulaSkin");
        SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceSaturatedTheme");
        
        conn.establecer_conexion();
        

    
        //CREACION DE LA TABLA
        modeloDeMiJTable = new DefaultTableModel() { 
        @Override 
        public Class getColumnClass(int c) { 
        return getValueAt(0, c).getClass(); 
        } 

        @Override 
        public boolean isCellEditable(int rowIndex, int columnIndex) { 
        return false; 
        }

        };
        modeloDeMiJTable.addColumn("NOMBRE INQ"); 
        modeloDeMiJTable.addColumn("NOMBRE PRO");
        modeloDeMiJTable.addColumn("MES"); 
        modeloDeMiJTable.addColumn("CANTIDAD");
        modeloDeMiJTable.addColumn("PAGO INQ");
        modeloDeMiJTable.addColumn("PAGO PRO");
        modeloDeMiJTable.addColumn("FECHA");
        
        jTable1.setModel(modeloDeMiJTable);
        
        
        int[] anchos = {100, 100, 30,80, 50, 25, 25};
        for(int i = 0; i < jTable1.getColumnCount(); i++) {

            //Sacamos el modelo de columnas de nuestra tabla

            //luego obtenemos la columna en la posicion "i"

            //invocamos el metodo setPreferrefWidth para ajustar el ancho

            //y le damos el valor del entero que esta en el arreglo en la posicion "i"

            jTable1.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }        
    modeloDeMiJTable.addRow(new Object[]{"","","","","","",""});        
    }
    

    
    
    static String integerFormat(int i) { 
        DecimalFormat df = new DecimalFormat("$#,###.##"); 
        String s = df.format(i); 
        return s; }
    //METODO QUE SITUA LA TABLA EN EL ULTIMO REGISTRO
////    public void scroll(){
////        int row =  jTable1.getRowCount () - 1;
////        Rectangle rect = jTable1.getCellRect(row, 0, true);
////        jTable1.scrollRectToVisible(rect);
////        jTable1.clearSelection();
////        jTable1.setRowSelectionInterval(row, row);
////        modeloDeMiJTable.fireTableDataChanged();
////    }
    public void limpiartabla(){
              DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
            int filas=jTable1.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
              }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel_egresos = new javax.swing.JLabel();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jComboBox_Mes = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_vlrtotal = new javax.swing.JLabel();
        jLabel_diferencia = new javax.swing.JLabel();
        jComboBox_Tipo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Cedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(dateChooserCombo1);
        dateChooserCombo1.setBounds(20, 90, 110, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Saldos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 20, 160, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Cedula");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 70, 60, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 830, 350);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1396514242_Search.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 80, 80, 40);

        jLabel_egresos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_egresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel_egresos);
        jLabel_egresos.setBounds(200, 470, 160, 40);
        getContentPane().add(dateChooserCombo2);
        dateChooserCombo2.setBounds(140, 90, 110, 30);

        jComboBox_Mes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox_Mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MES", "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO" }));
        jComboBox_Mes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_MesItemStateChanged(evt);
            }
        });
        jComboBox_Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_Mes);
        jComboBox_Mes.setBounds(260, 90, 110, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Fecha Mes");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 50, 160, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Desde");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 70, 160, 20);

        jLabel_vlrtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_vlrtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel_vlrtotal);
        jLabel_vlrtotal.setBounds(200, 430, 160, 40);

        jLabel_diferencia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_diferencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel_diferencia);
        jLabel_diferencia.setBounds(200, 510, 160, 40);

        jComboBox_Tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox_Tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "INQUILINO", "PROPIETARIO" }));
        jComboBox_Tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_TipoItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox_Tipo);
        jComboBox_Tipo.setBounds(390, 90, 130, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Hasta");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 70, 160, 20);
        getContentPane().add(jTextField_Cedula);
        jTextField_Cedula.setBounds(530, 90, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vlrtotal=0;
        egresos=0;
        String buscar1= "",buscar2= "", consulta="", pago_i="", pago_p="";
        
//        if(validador==0){
        consulta="select inq.nombres, pro.nombres, ca.mes, ca.cantidad, ca.pago_i, ca.pago_p, ca.fecha "
                + "from propietarios as pro INNER JOIN  causacion as ca on ca.cod_propietario = pro.cod_propietario INNER JOIN inquilinos as inq on  ca.cod_inquilino = inq.cod_inquilino   "
                + "where ca.fecha::Date between '"+dateChooserCombo1.getText()+"' and '"+dateChooserCombo2.getText()+"' " ;
        if(!mes.equals("")){
           buscar1=" and ca.mes = '"+mes+"'";
        }
        if(!usuario.equals("")){
            if(jTextField_Cedula.getText().equals("")){
                conn.JOptionShowMessage("+1", "", "Ingrese la Cedula del "+jComboBox_Tipo.getSelectedItem());
            }
            else{
                buscar2=" and "+usuario+" = "+jTextField_Cedula.getText()+"";
            }
           
           
        }        
        consulta = consulta+buscar1+buscar2;
        System.out.println(consulta);
        limpiartabla();
        ResultSet n=conn.consulta(consulta);
        try{
            while(n.next()){
                if(n.getInt(5)==2){
                    pago_i="DEBE";
                }
                else if(n.getInt(5)==1){
                    pago_i="PAGO";
                }
                if(n.getInt(6)==2){
                    pago_p="DEBE";
                }
                else if(n.getInt(6)==1){
                    pago_p="PAGO";
                }                
                modeloDeMiJTable.addRow(new Object[]{n.getString(1),n.getString(2),n.getString(3),n.getString(4),pago_i,pago_p,n.getString(7)});
            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_MesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_MesItemStateChanged
      if(jComboBox_Mes.getSelectedIndex()==0){
          mes="";
      }        
      else if(jComboBox_Mes.getSelectedIndex()==1){
          mes="ENERO";
      }  
      else if(jComboBox_Mes.getSelectedIndex()==2){
          mes="FEBRERO";
      }  
      else if(jComboBox_Mes.getSelectedIndex()==3){
          mes="MARZO";
      }  
      else if(jComboBox_Mes.getSelectedIndex()==4){
          mes="ABRIL";
      }  
      else if(jComboBox_Mes.getSelectedIndex()==5){
          mes="JUNIO";
      }  
      else if(jComboBox_Mes.getSelectedIndex()==6){
          mes="JULIO";
      }        
    }//GEN-LAST:event_jComboBox_MesItemStateChanged

    private void jComboBox_TipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_TipoItemStateChanged
        if(jComboBox_Tipo.getSelectedIndex()==0){
          usuario="";
        } 
        else if(jComboBox_Tipo.getSelectedIndex()==1){
        usuario="inq.cedula";
        }  
        else if(jComboBox_Tipo.getSelectedIndex()==2){
          usuario="pro.cedula";
        }
    }//GEN-LAST:event_jComboBox_TipoItemStateChanged

    private void jComboBox_MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MesActionPerformed

    /**
     * @param args the command line arguments
     */

int vlrtotal=0;
int egresos=0;
int diferencia=0;
Conexion conn = new Conexion();
String buscar="", buscar2="",mes = "", usuario="";
int validador =0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_Mes;
    private javax.swing.JComboBox jComboBox_Tipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_diferencia;
    private javax.swing.JLabel jLabel_egresos;
    private javax.swing.JLabel jLabel_vlrtotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Cedula;
    // End of variables declaration//GEN-END:variables
}
