/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliaria_fase01;

import Cartera_y_caja.Cartera;
import Cartera_y_caja.Index;

/**
 *
 * @author Usuario
 */
public class Pantalla_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Inicial
     */
    public Pantalla_Inicial() {
        initComponents();
        setSize(900,600);
        setLocationRelativeTo(null);
        setResizable(false);
        jLabel1.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoppal.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 0, 1260, 240);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ADMINISTRATIVO.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 380, 290, 140);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CARTERA Y CAJA.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 240, 290, 140);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CONTABILIDAD.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 240, 290, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Conexion.dialog();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Index dialog = new Index(new javax.swing.JFrame(), true);
                  //Cartera dialog = new Cartera(new javax.swing.JFrame(), true);
                
                dialog.setVisible(true);
            }
        });

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
